# Survival configuration file
#
# Server lock down?
lock-down: false
#
# Do we use default permission message or custom ?
perm-message:
  default: true
  format: "&a&l>> &7Sorry, no permissions for this feature."
#
# Server Message of The Day. For list ping and in-game
MOTD:
  server-list: "&a&lSurvival &2&lServer &a&l&k|||"
  motd:
  - "&7     ----- &a&lSurvival Server &7-----"
  - "&bWelcome back, &f%player%&b!"
  - "&7> &fThere are &a%online_players% &fout of &3%max_players% &fonline&3!"
  - "&7The time and date is: &a%time%"
  - "&7> Use /help"
#
#
kick-format: "&f%player% &chas been kicked. &cReason: &f%msg%"
#
broadcast:
  format: ""
  sound: false
  sounds:
#
#
messaging:
  format:
    from: "&6[&4PM&6]&r &6From: &a%sender% &f%msg%"
    to: "&6[&4PM&6]&r &6To: &c%target% &f%msg%"
#
Chat:
  Enabled: true
  msg: "&7Chat has been set to &a%value%&7."
  chat-disabled: "&7The chat has been &asilenced."
  no-permission: "&cYou don't have permission to speak here. &4/msg only."
  custom-chat:
    Enabled: true
    Format: "&0[&8%world%&0] &7%name% &a&l> &7%msg%"
#
#
list:
  messages: "&cError: No staff members online. &b&o.-."
  format:
  - "&a---------- &2Survival &aServer &a----------"
  - "&7Online:&a %online_players%/%max_players%"
  - "&cStaff online: &a%staff%"
  - "&bCurrent Time: &f%time%"
  - "&7------------------------------"

#
#
Messages:
  join: "&bJoin&a> &7{player}"
  quit: "&8Quit&a> &7{player}"

# # # # # # # # # # # #
Whitelist:
  kick-message: "&9Whitelist&8> &c&oConnection failed: &8&l--&a&l>\n&6&lUUID: &7(&a%uuid%&7)\n&6&lUsername: &c&n%playername%"
  whitelist-alert: "&aWhitelist&7> &7The player, &a%playername% is attempting to join the server."
#
#
use-default-msg: true
restriction-msg: "&6This has been disabled."
#
blocked-cmds:
  - /deop
  - /op
  - /rl
  - /reload
  - /stop
  - /about
  - /kill
  - /ban
  - /mute
  - /core
  - /eco
  - /
  - /?
  - //
  - /we
  - //we
  - /wg
  - /worldguard
  - /region
  - /ban-ip
  - /banip
  - /pl
  - /plugins
  - /whois
  - /seen
  - /playerlock
  - /lock
  - /pardon
  - /banlist
  - /tpall
  - /toggledownfall
  - /tellraw
  - /save-on
  - /save-all
  - /pex
  - /promote
  - /motdlist
  - /serverlist
  - /pardon-ip
  - /unbanip
  - /pardonip
  - /weather
  - /ver
  - /version
  - /about
