# Survival configuration file
#
server-lock: false
#
# Don't fucking touch this unless you know what you're doing.
Permissions:
  use-default: true
# Do we use default permission message or custom ?
perm-message:
  default: true
  format: "&a&l>> &7Sorry, no permissions for this feature."
#
# Server Message of The Day. For list ping and in-game
MOTD:
  server-list: "&a&l<> &cBajr&7Craft &a&l<>"
  motd:
  - "&7     ----- &a&l<> &cBajr&7Craft &a&l <> &7-----"
  - "&bWelcome, &f%player%&b! &a%online_players%/%max_players%"
  - "&4&nRULES&r: &fDiscord: &bhttps://discord.gg/54H9J2"
  - "&7This is a &c&nfriendly&r server."
  - "&7No greifing, trolling, or attacking others."
  - "&4&nNO&r AFK fish farming until further notice."
#
#
kick-format: "&f%player% &chas been kicked. &cReason: &f%msg%"
#
Broadcast:
  format: "&f&5Alert&r> {msg}"

#
# Don't fucking touch the use permission value.
# Unless you know exactly what you are doing.
Whitelist:
  use-permission: false
  permission: "utils.specific.permission"
  kick-message: "&9Whitelist&8> &cYou are not whitelisted, &c&n{name}.\n&cContact Miskey on Discord."
  whitelist-alert: "&6Alert&7&l> &6&l{name}, &7is not Whitelisted!"
  enforce-kick: "&4Server whitelist was enforced by an Admin!"
  enforce: "&4{admin}> &7whitelist enforce success!"
#
#
Chat:
  Enabled: true
  msg: "&7Chat has been set to &a%value%&7."
  chat-disabled: "&7The chat has been &asilenced."
  no-permission: "&cYou don't have permission to speak here. &4/msg only."
  custom-chat:
    Enabled: false
    Format: "&7{name}> &r%msg%"
  functions:
    world:
      use-text: true
    location:
      use-text: true
    exp:
      use-text: true

#
#
list:
  messages: "&cError: No staff members online. &b&o.-."
  format:
  - "&a-------- &a&l<> &cBajr&7Craft &a&l <> &a--------"
  - "&7Online:&a %online_players%/%max_players%"
  - "&cStaff online: &a%staff%"
  - "&bCurrent Time: &f%time%"
  - "&7------------------------------"

#
#
Messages:
  join: "&8[&a&l+&8] &7{player}"
  quit: "&8[&4&l-&8] &7{player}"

# # # # # # # # # # # #
Whitelist:
  kick-message: "&9Whitelist&8> &7You are not whitelisted, &ahttps://discord.gg/QJgqcts to request access."
  whitelist-alert: "&aWhitelist&7> &7The player, &a{name} &7is attempting to join the server."
#
#
use-default-msg: true
restriction-msg: "&6This has been disabled."
#
blocked-cmds:
  - /deop
  - /op
  - /rl
  - /reload
  - /stop
  - /about
  - /kill
  - /ban
  - /mute
  - /core
  - /eco
  - /
  - /?
  - //
  - /we
  - //we
  - /wg
  - /worldguard
  - /region
  - /ban-ip
  - /banip
  - /pl
  - /plugins
  - /whois
  - /seen
  - /playerlock
  - /lock
  - /pardon
  - /banlist
  - /tpall
  - /toggledownfall
  - /tellraw
  - /save-on
  - /save-all
  - /pex
  - /promote
  - /motdlist
  - /serverlist
  - /pardon-ip
  - /unbanip
  - /pardonip
  - /weather
  - /ver
  - /version
  - /about
  - /gamemode 1
  - /gamemode creative        
#
blocked-words:
  - faggot
  - faggit
  - nigger
  - NIGGER
  - niggerslayer
  - fag
  - FAG
  - KILLNIGGERS
  - killniggers
  - NIGGERKIllers
  - niggerkillers
  - NlGGER
  - NiggerHunter
  - HuntingNiggers
  - HuntNiggers
  - KillNiggers
  - Niggers
  - niggers
  - Niggert
  - Niggernigger