name: Survival
main: me.ES96.Survival.com.Survival
version: 1.2.1
description: Survival server plugin
author: SendCoffee
website: https://github.com/ES359/Survival

commands:
  chat:
    description: Chat management command.
    aliases: [talk,c,shutup]
  kick:
    description: Command that kicks a player from the server.
    aliases: [bye, goodbye, fuckoff]
  list:
    description: Command that lists the players/staff members on the server.
    aliases: [who, slist, users]
  message:
    description: Command to private message between players.
    aliases: [yell, msg, hi, hello]
  tp:
    description: Command to teleport to player.
    aliases: [stp, teleport]
  tphere:
    description: Command to teleport player to you.
    aliases: [teleporthere, comehere, call]
  whitelist:
    description: Whitelist command to manage server whitelist.
    aliases: [wl]
  cmddisable:
    description: Administration command for CMD-Disable
    aliases: [cmd, cdisable, cd]
  edit:
    description:
    aliases: [ed,modify,set]

permissions:

  Survival.*:
    description: Gives access completely to Survival plugin.
    children:
      Survival.set.*: true
      Survival.command.*: true
      Survival.bypass.*: true
      Survival.mode.*: true
      Survival.gamemodes.*: true
      Survival.chat.format: true

  Survival.chat.format:
    description: Gives all access to chat formatting.
    children:
      Survival.chat.world: true
      Survival.chat.color: true
      Survival.chat.location: true
      Survival.chat.exp: true

  Survival.set.*:
    description: Access to set flag.
    children:
      Survival.set.Survival: true
      Survival.set.break: true
      Survival.set.place: true
      Survival.set.interact: true
      Survival.set.drop: true
      Survival.set.pickup: true
      Survival.warp.set: true
      Survival.set.chat: true
      Survival.set.tnt: true
      Survival.mode.set: true

  Survival.mod:
    description: Given to moderators...
    children:
      Survival.tp: true
      Survival.tphere: true
      Survival.tptoggle: true
      Survival.vanish: true
      Survival.mode.*: true
      Survival.world.kick: true
      Survival.chat.clear: true
      Survival.whitelist.notify: true
      Survival.chat.clearothers: true


  Survival.member:
    description: Given to trusted memebers on the server.
    children:
      Survival.chat: true
      Survival.chat.clearself: true
      Survival.ci: true
      Survival.access: true
      Survival.guest: true

  Survival.guest:
    description: Usually given to guest users on Survival server...
    children:
      Survival.spawn: true
      Survival.message: true
      Survival.help: true
      Survival.chat: true
      Survival.list: true

  Survival.command.*:
    description: Access to Survival commands.
    children:
      Survival.set: true
      Survival.tp: true
      Survival.tphere: true
      Survival.tptoggle: true
      Survival.whitelist.notify: true
      Survival.whitelist: true
      Survival.staffchat: true
      Survival.help: true
      Survival.chat: true
      Survival.chat.clearself: true
      Survival.chat.clear: true
      Survival.reload: true
      Survival.toggle: true
      Survival.message: true
      Survival.mode.set: true
      Survival.mode.set.others: true
      Survival.ci: true
      Survival.users: true
      Survival.item: true
  survival.bypass:
    description: Access to bypass permissions.
    children:
      Survival.bypass.chat: true
      Survival.bypass.place: true
      Survival.bypass.break: true
      Survival.bypass.interact: true
      Survival.bypass.drop: true
      Survival.bypass.pickup: true
      Survival.bypass.toggle: true
  Survival.spawn:
    description: Main command to return to spawn.
    default: true
  Survival.help:
    description: Main command for help
    default: true